apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: elearning
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ChangeThisPassword
  POSTGRES_DB: elearning
