name: FastAPI Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./E-learing-fastapi

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate Python code
        run: |
          python -m compileall .

      - name: Check Docker Hub username
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "ERROR: DOCKERHUB_USERNAME is empty"
            exit 1
          fi

          if [[ "${{ secrets.DOCKERHUB_USERNAME }}" =~ [^a-z0-9_.-] ]]; then
            echo "ERROR: DOCKERHUB_USERNAME contains invalid characters"
            exit 1
          fi

          echo "Docker Hub username is valid"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/elearning-fastapi:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/elearning-fastapi:latest
