name: FastAPI Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./E-learing-fastapi

    steps:

      # --------------------------------
      # Checkout
      # --------------------------------

      - name: Checkout code
        uses: actions/checkout@v4


      # --------------------------------
      # Python
      # --------------------------------

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      # --------------------------------
      # Install dependencies
      # --------------------------------

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # --------------------------------
      # Validate Python
      # --------------------------------

      - name: Validate Python code
        run: |
          python -m compileall .


      # --------------------------------
      # Docker Hub Login
      # --------------------------------

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # --------------------------------
      # Build Docker Image
      # --------------------------------

      - name: Build Docker image
        run: |
          docker build \
            -t jenishselvaraj/crud-app:${{ github.sha }} .


      # --------------------------------
      # Push Docker Image
      # --------------------------------

      - name: Push Docker image
        run: |
          docker push \
            jenishselvaraj/crud-app:${{ github.sha }}


      # --------------------------------
      # AWS Credentials
      # --------------------------------

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # --------------------------------
      # Configure kubectl
      # --------------------------------

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}


      # --------------------------------
      # Check EKS
      # --------------------------------

      - name: Check EKS connection
        run: |
          kubectl get nodes


      # --------------------------------
      # Deploy PostgreSQL Secret
      # --------------------------------

      - name: Deploy PostgreSQL Secret
        run: |
          kubectl apply -f ../postgres-secret.yaml


      # --------------------------------
      # Deploy PostgreSQL
      # --------------------------------

      - name: Deploy PostgreSQL
        run: |
          kubectl apply -f ../postgres-deployment.yaml
          kubectl apply -f ../postgres-service.yaml


      # --------------------------------
      # Deploy FastAPI
      # --------------------------------

      - name: Deploy FastAPI
        run: |
          kubectl apply -f ../deployment.yaml
          kubectl apply -f ../service.yaml


      # --------------------------------
      # Update FastAPI Image
      # --------------------------------

      - name: Update Docker image
        run: |
          kubectl set image deployment/crud-app \
            crud-app=jenishselvaraj/crud-app:${{ github.sha }} \
            -n elearning


      # --------------------------------
      # Wait for Rollout
      # --------------------------------

      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/crud-app \
            -n elearning \
            --timeout=180s


      # --------------------------------
      # Check Pods
      # --------------------------------

      - name: Check pods
        run: |
          kubectl get pods -n elearning -o wide


      # --------------------------------
      # Check Services
      # --------------------------------

      - name: Check services
        run: |
          kubectl get svc -n elearning


      # --------------------------------
      # Debug if deployment fails
      # --------------------------------

      - name: Debug deployment
        if: failure()
        run: |
          echo "===== PODS ====="
          kubectl get pods -n elearning -o wide

          echo "===== DEPLOYMENT ====="
          kubectl describe deployment crud-app -n elearning

          echo "===== POD DESCRIBE ====="
          kubectl describe pods -n elearning

          echo "===== EVENTS ====="
          kubectl get events \
            -n elearning \
            --sort-by=.lastTimestamp

          echo "===== APPLICATION LOGS ====="
          kubectl logs \
            -n elearning \
            -l app=crud-app \
            --tail=100
